pool:
  vmImage: 'Ubuntu 16.04'

variables:
  - group: FolderStorage

steps:
- script: |
    sudo wget https://julialang-s3.julialang.org/bin/linux/x64/${MYJULIA_VERSION_MINOR}/julia-${MYJULIA_VERSION}-linux-x86_64.tar.gz
    sudo mkdir -p /opt/julia
    sudo tar --strip-components=1 -xzvf julia-${MYJULIA_VERSION}-linux-x86_64.tar.gz -C /opt/julia

    sudo wget https://releases.hashicorp.com/packer/${MYPACKER_VERSION}/packer_${MYPACKER_VERSION}_linux_amd64.zip
    sudo mkdir -p /opt/packer
    sudo unzip packer_1.3.4_linux_amd64.zip -d /opt/packer

    mkdir -p $(HOME)/.julia/dev

    cp -r ${BUILD_SOURCESDIRECTORY} $(HOME)/.julia/dev/FolderStorage

    AUTH=$(echo -n ":$MYPAT" | openssl base64 | tr -d '\n')
    git -c http.https://chevron.visualstudio.com/ETC-ESD-AbstractStorage.jl/_git/AbstractStorage.jl.extraheader="AUTHORIZATION: basic $AUTH" clone https://chevron.visualstudio.com/ETC-ESD-AbstractStorage.jl/_git/AbstractStorage.jl /home/vsts/.julia/dev/AbstractStorage

    /opt/julia/bin/julia -e 'using Pkg; pkg"add Random Serialization"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"develop --local $(HOME)/.julia/dev/AbstractStorage"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"develop --local $(HOME)/.julia/dev/FolderStorage"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"build FolderStorage"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"precompile"'
  env:
    MYPAT: $(PAT)
    MYJULIA_VERSION: $(JULIA_VERSION)
    MYJULIA_VERSION_MINOR: $(JULIA_VERSION_MINOR)
    MYPACKER_VERSION: $(PACKER_VERSION)
  displayName: 'Install system'

- script: |
    /opt/julia/bin/julia -e 'using Pkg; pkg"test FolderStorage"'
  displayName: 'Run unit-tests'

- task: DownloadSecureFile@1
  inputs:
    secureFile: account.json

- task: DownloadSecureFile@1
  inputs:
    secureFile: id_rsa

- script: |
    AUTH=$(echo -n ":$MYPAT" | openssl base64 | tr -d '\n')
    git -c http.https://chevron.visualstudio.com/ETC-ESD-jcloud/_git/jcloud.extraheader="AUTHORIZATION: basic $AUTH" clone https://chevron.visualstudio.com/ETC-ESD-jcloud/_git/jcloud /tmp/jcloud
    cd /tmp/jcloud
    cp $(Agent.TempDirectory)/id_rsa ./ssh/id_rsa
    cp $(Agent.TempDirectory)/account.json ./account.json
    /opt/packer/packer build --force jcloud.json
  env:
    MYPAT: $(PAT)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/head/master'))
  displayName: 'Deploy to Google Cloud Platform'
