pool:
  vmImage: 'Ubuntu 16.04'

variables:
  - group: FolderStorage

steps:
- script: |
    sudo wget https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz
    sudo mkdir -p /opt/julia
    sudo tar --strip-components=1 -xzvf julia-1.1.0-linux-x86_64.tar.gz -C /opt/julia

    mkdir -p $(HOME)/.julia/dev

    cp -r ${BUILD_SOURCESDIRECTORY} $(HOME)/.julia/dev/FolderStorage

    AUTH=$(echo -n ":$MYPAT" | openssl base64 | tr -d '\n')
    git -c http.https://chevron.visualstudio.com/ETC-ESD-AbstractStorage.jl/_git/AbstractStorage.jl.extraheader="AUTHORIZATION: basic $AUTH" clone https://chevron.visualstudio.com/ETC-ESD-AbstractStorage.jl/_git/AbstractStorage.jl /home/vsts/.julia/dev/AbstractStorage

    /opt/julia/bin/julia -e 'using Pkg; pkg"add Random Serialization"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"develop --local $(HOME)/.julia/dev/AbstractStorage"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"develop --local $(HOME)/.julia/dev/FolderStorage"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"build FolderStorage"'
    /opt/julia/bin/julia -e 'using Pkg; pkg"precompile"'
  env:
    MYPAT: $(PAT)
  displayName: 'Install system'
  
- script: |
    /opt/julia/bin/julia -e 'using Pkg; pkg"test FolderStorage"'
  displayName: 'Run unit-tests'
